/* xppautX's configure-equivalent for the unmodified TinyCC source (W254).
   The compiler's target macros select the native ABI. */
#ifndef XPP_TINYCC_CONFIG_H
#define XPP_TINYCC_CONFIG_H

#define TCC_VERSION "0.9.28rc"
#define ONE_SOURCE 1
#if defined(__x86_64__)
#define TCC_TARGET_X86_64 1
#elif defined(__aarch64__)
#define TCC_TARGET_ARM64 1
#else
#error xppautX embeds TinyCC only for x86_64 and arm64
#endif
#if defined(_WIN32)
#define TCC_TARGET_PE 1
#elif defined(__APPLE__)
#define TCC_TARGET_MACHO 1
#elif !defined(__linux__)
#error xppautX embeds TinyCC only for Windows, macOS and Linux
#endif

/* Symbols come from the adapter, never the host's dynamic loader or TinyCC's
   small built-in libc symbol table. No installed compiler files are needed. */
#define CONFIG_TCC_STATIC 1
#define CONFIG_TCCBOOT 1
#define CONFIG_TCCDIR ""
#define CONFIG_TCC_SYSINCLUDEPATHS ""
#define CONFIG_TCC_LIBPATHS ""
#define CONFIG_TCC_CRTPREFIX ""
/* Embed the predefined C declarations generated by upstream's c2str. */
#define CONFIG_TCC_PREDEFS 1
/* No runtime support objects for instrumentation or stack backtraces. */
#define CONFIG_TCC_BCHECK 0
#define CONFIG_TCC_BACKTRACE 0
/* Write code before making it executable, on every platform. */
#define CONFIG_RUNMEM_RO 1
/* This revision passes nonzero size to VirtualFree(MEM_RELEASE), which leaks
   on Windows. Select upstream's malloc/VirtualProtect/free path instead. */
#define CONFIG_RUNMEM_VIRTUALALLOC 0

#endif
