/* A hello with the command table and key layers the tests use (the core's own:
   core/command_table.h, core/menus.cpp, core/ui_json.cpp's command table). Not a test itself. */
import type {CommandRow} from '../src/protocol/kinds';
import {PROTOCOL, type HelloEvent, type MenuName} from '../src/protocol/types';
import {initialState, reduce} from '../src/store/state';

/** [menu, key, id, kind, category, pinnable, default key]: the core's own table (core/command_table.h) */
const COMMAND_TUPLES: [MenuName, string, string, string, string, boolean, string?][] = [
  ['main', 'i', 'initialconds', 'x', 'run', true],
  ['main', 'c', 'continue', 'x', 'run', true],
  ['main', 'p', 'parameters', 's', 'run', true],
  ['num', 't', 'total', 's', 'run', true],
  ['num', 's', 'start', 's', 'run', true],
  ['num', 'r', 'transient', 's', 'run', true],
  ['num', 'd', 'dt', 's', 'run', true],
  ['num', 'm', 'method', 's', 'run', true],
  ['num', 'o', 'store_every', 's', 'run', true],
  ['num', 'b', 'bounds', 's', 'run', true],
  ['file', 'm', 'openmodel', 'd', 'files', true, 'Ctrl+O'],
  ['file', 'n', 'opensession', 'd', 'files', true],
  ['file', 'v', 'savesession', 'd', 'files', true, 'Ctrl+S'],
  ['file', 'e', 'reload', 'd', 'files', true],
  ['file', 'r', 'importset', 'd', 'files', true],
  ['file', 's', 'saveinfo', 'd', 'files', true],
  ['file', 'q', 'quit', 'c', 'files', false],
  ['main', 's', 'singpts', 'x', 'analysis', true],
  ['main', 'n', 'nullcline', 'v', 'analysis', true],
  ['main', 'd', 'dirfield', 'v', 'analysis', true],
  ['main', 'b', 'bndryval', 'x', 'analysis', true],
  ['file', 'a', 'auto', 'v', 'analysis', true],
  ['num', 'n', 'ncline', 's', 'analysis', true],
  ['num', 'i', 'singpt', 's', 'analysis', true],
  ['num', 'e', 'delay', 's', 'analysis', true],
  ['num', 'h', 'stochastic', 'd', 'analysis', true],
  ['num', 'p', 'poincare', 's', 'analysis', true],
  ['num', 'u', 'ruelle', 's', 'analysis', true],
  ['num', 'v', 'bndval', 's', 'analysis', true],
  ['num', 'a', 'averaging', 'd', 'analysis', true],
  ['main', 'w', 'window', 'v', 'plot', true],
  ['main', 'a', 'phasespace', 'd', 'plot', true],
  ['main', 'g', 'graphic', 'v', 'plot', true],
  ['main', 'v', 'viewaxes', 'v', 'plot', true],
  ['main', 'x', 'xivst', 'v', 'plot', true],
  ['main', 't', 'text', 'v', 'plot', true],
  ['main', 'm', 'makewindow', 'v', 'plot', true],
  ['main', 'r', 'restore', 'v', 'plot', true],
  ['main', '3', '3dparams', 'v', 'plot', true],
  ['main', 'e', 'erase', 'v', 'plot', true],
  ['main', 'k', 'kinescope', 'v', 'plot', true],
  ['num', 'c', 'colorcode', 'v', 'plot', true],
  ['file', 'p', 'source', 'v', 'tools', true],
  ['file', 'c', 'calculator', 'v', 'tools', true],
  ['file', 't', 'transpose', 'd', 'tools', true],
  ['file', 'g', 'getparset', 's', 'tools', true],
  ['file', 'l', 'clone', 'd', 'tools', true],
  ['file', 'x', 'xpprc', 'd', 'tools', true],
  ['file', 'u', 'tutorial', 'v', 'tools', true],
  ['file', 'o', 'copyset', 'v', 'tools', true],
  ['file', 'd', 'record', 'd', 'tools', true],
  ['file', 'y', 'play', 'd', 'tools', true],
  ['file', 'h', 'help', 'v', 'tools', true],
  ['num', 'k', 'lookup', 'd', 'tools', true],
  ['main', 'f', 'file', 'v', 'layer', false],
  ['main', 'u', 'numerics', 'v', 'layer', false],
  ['num', '\x1b', 'exit', 'v', 'layer', false],
];

const layer = (keys: string, kinds: string, ids: string[]) => ({items: ids, keys, kinds, hints: ids, ids});

export const HELLO: HelloEvent = {
  ev: 'hello',
  state_inspection: {tail_intervals: 10}, protocol: PROTOCOL, features: [], title: 't', file: 'f.ode', about: '',
  output_names: {par: 'lecar.par', ic: 'lecar.ic', csv: 'lecar.csv', curves: 'lecar-curves.csv'},
  continue: {grid_tolerance: 1e-6},
  steady: {max_decimals: 15, default_decimals: 9, default_hold: 1},
  quit: {question: 'Quit?', recording: 'Quit and stop recording?', choices: ['Save session', "Don't save"], keys: 'sd'},
  lists: [], userbuttons: [], defaults: {pars: [], ics: []},
  menu_names: ['main', 'file', 'num'],
  command_categories: [
    {id: 'run', label: 'Run', listed: true}, {id: 'files', label: 'Files', listed: true},
    {id: 'analysis', label: 'Analysis', listed: true}, {id: 'plot', label: 'Plot', listed: true},
    {id: 'tools', label: 'Tools', listed: true}, {id: 'layer', label: 'Shortcut layer', listed: false}],
  command_table: COMMAND_TUPLES.map(([menu, key, id, kind, category, pinnable, chord]): CommandRow => ({
    menu, id, key, label: id, description: `Action ${id}`, kind, category, pinnable, default_keys: chord ? [chord] : [],
    legacy_keys: [...menu === 'main' ? [] : [menu === 'file' ? 'F' : 'U'], key === '' ? 'Esc' : key.toUpperCase()]})),
  windows: {
    auto: layer('panrgucdf', 'svsxdsvvv', ['param', 'axes', 'numerics', 'run', 'grab', 'usr', 'clear', 'redraw', 'file']),
    ani: layer('fgrsmoa', 'vvvvdvd', ['file', 'go', 'reset', 'skip', 'mpeg', 'fly', 'grab']),
    browser: layer('fgru', 'vvdd', ['find', 'get', 'replace', 'unreplace']),
    aplot: layer('refrpg', 'vvvvdd', ['redraw', 'edit', 'fit', 'range', 'print', 'gif']),
    equilibrium: layer('i', 's', ['import']),
  },
  commands: [
    {cmd: 'steady', kind: 'x', step: true}, {cmd: 'continue', kind: 'x', step: true},
    {cmd: 'key', kind: '', step: true},
    {cmd: 'answer', kind: 'c', step: false}, {cmd: 'abort', kind: 'c', step: false},
    {cmd: 'state', kind: 'v', step: false}, {cmd: 'data', kind: 'v', step: false},
    {cmd: 'display', kind: 'v', step: true}, {cmd: 'click', kind: 'v', step: true},
    {cmd: 'browser', op: 'write', kind: 'd', step: true}, {cmd: 'browser', kind: 'v', step: false},
    {cmd: 'set', kind: 's', step: true}, {cmd: 'slider', kind: 's', step: true},
    {cmd: 'auto', op: 'set', kind: 's', step: true}, {cmd: 'auto', op: 'grab', kind: 'd', step: true},
    {cmd: 'auto', kind: 'v', step: true},
    {cmd: 'values', op: 'write', kind: 'd', step: true}, {cmd: 'values', kind: 's', step: true},
    {cmd: 'userbut', kind: 'x', step: true},
  ],
  upload_error: 'larger than 64 MB',
  player_speed: {min: 0.25, max: 8},
  limits: {upload: 64 * 1024 * 1024, browser_rows: 2000, browser_cols: 500},
  window_ids: {plots: 21, auto: 101, ani: 104, aplot: 105},
};

/** the state after the server's hello: every event but hello comes after one */
export const READY = reduce(initialState, {type: 'event', ev: HELLO});
