/* embed_bytes: write one file into a C source as a byte array, for a build
   step that wants a single small blob (xpp_window.cpp's Linux fallback
   icon, W13b) rather than tools/embed.c's web2/dist asset table.
   usage: embed_bytes out.c symbol file
   Writes `const unsigned char SYMBOL[]` and `const unsigned long SYMBOL_len`. */
#include <stdio.h>

int main(int argc, char **argv)
{
    FILE *out, *in;
    size_t n = 0;
    int c;
    if (argc != 4) {
        fprintf(stderr, "usage: embed_bytes out.c symbol file\n");
        return 2;
    }
    in = fopen(argv[3], "rb");
    if (!in) {
        fprintf(stderr, "embed_bytes: cannot read %s\n", argv[3]);
        return 1;
    }
    out = fopen(argv[1], "w");
    if (!out) {
        fclose(in);
        return 1;
    }
    fprintf(out, "/* generated by tools/embed_bytes.c from %s: do not edit */\n", argv[3]);
    fprintf(out, "const unsigned char %s[] = {", argv[2]);
    while ((c = fgetc(in)) != EOF) {
        fprintf(out, "%s%s%d", n ? "," : "", n % 24 ? "" : "\n", c);
        n++;
    }
    fprintf(out, "%s0};\n", n ? "," : "");
    fprintf(out, "const unsigned long %s_len = %luUL;\n", argv[2], (unsigned long)n);
    fclose(in);
    fclose(out);
    return 0;
}
