#pragma once
/* Build tools cannot link the core's I/O (it is still being built).
   Own the byte-to-source conversion here, shared by both generators. */
#include <fstream>
#include <iomanip>
#include <ostream>
#include <stdexcept>
#include <string>
#include <string_view>

namespace xpp::embed {
// Keep generated lines short enough to inspect without horizontal scrolling.
inline constexpr std::size_t bytes_per_line = 24;

inline void write_bytes(std::ostream &out, std::string_view symbol, const char *path)
{
    std::ifstream in(path, std::ios::binary);
    if (!in) throw std::runtime_error(std::string(path) + ":1: cannot open embedded file");
    in.exceptions(std::ios::badbit);
    out << "constexpr unsigned char " << symbol << "[] = {";
    std::size_t n = 0;
    char byte;
    while (in.get(byte)) {
        out << (n ? "," : "") << (n % bytes_per_line ? "" : "\n")
            << static_cast<unsigned int>(static_cast<unsigned char>(byte));
        ++n;
    }
    if (!in.eof()) throw std::runtime_error(std::string(path) + ":1: cannot read embedded file");
    // A spare byte permits empty inputs; spans exclude it from the payload.
    out << (n ? "," : "") << "0};\n";
}

inline std::ofstream output(const char *path)
{
    std::ofstream out;
    out.exceptions(std::ios::failbit | std::ios::badbit);
    out.open(path);
    out << "// Generated by tools/embed*.cpp; do not edit.\n"
           "#include \"xpp_assets.h\"\nnamespace xpp {\nnamespace {\n";
    return out;
}
}
