/* embed: write the web front end's files into a C source as byte arrays
   for xpp_http.c. Build step only (Makefile rule for web_assets.c).
   usage: embed out.c web/index.html web/xpp-client.js ... */
#include <stdio.h>
#include <string.h>

static const char *type_of(const char *path)
{
    const char *dot = strrchr(path, '.');
    if (dot && strcmp(dot, ".html") == 0) return "text/html; charset=utf-8";
    if (dot && strcmp(dot, ".js") == 0) return "text/javascript; charset=utf-8";
    if (dot && strcmp(dot, ".css") == 0) return "text/css; charset=utf-8";
    return "application/octet-stream";
}

int main(int argc, char **argv)
{
    FILE *out;
    int i, c;
    if (argc < 3) {
        fprintf(stderr, "usage: embed out.c file...\n");
        return 2;
    }
    out = fopen(argv[1], "w");
    if (!out) return 1;
    fprintf(out, "/* generated by tools/embed.c from the web/ files: do not edit */\n"
                 "#include <stddef.h>\n"
                 "typedef struct { const char *path, *type; const unsigned char *data; size_t len; } XppWebAsset;\n");
    for (i = 2; i < argc; i++) {
        FILE *in = fopen(argv[i], "rb");
        size_t n = 0;
        if (!in) {
            fprintf(stderr, "embed: cannot read %s\n", argv[i]);
            return 1;
        }
        fprintf(out, "static const unsigned char a%d[] = {", i);
        while ((c = fgetc(in)) != EOF) {
            fprintf(out, "%s%s%d", n ? "," : "", n % 24 ? "" : "\n", c);
            n++;
        }
        fprintf(out, "%s0};\n", n ? "," : "");
        fclose(in);
    }
    fprintf(out, "const XppWebAsset xpp_web_assets[] = {\n");
    for (i = 2; i < argc; i++) {
        const char *base = strrchr(argv[i], '/');
        base = base ? base + 1 : argv[i];
        FILE *in = fopen(argv[i], "rb");
        long len;
        fseek(in, 0, SEEK_END);
        len = ftell(in);
        fclose(in);
        fprintf(out, "  {\"/%s\", \"%s\", a%d, %ld},\n", strcmp(base, "index.html") == 0 ? "" : base,
                type_of(base), i, len);
    }
    fprintf(out, "  {0, 0, 0, 0}\n};\n");
    fclose(out);
    return 0;
}
