/* embed: write the web front ends' files into a C source as byte arrays
   for xpp_http.c. Build step only (Makefile rule for web_assets.c).
   usage: embed out.c web/index.html web/xpp-client.js ... --prefix=/v2/ web2/dist/index.html ...
   A file is served at the prefix (initially "/") plus its base name;
   index.html at the prefix itself. */
#include <stdio.h>
#include <string.h>

static const char *type_of(const char *path)
{
    const char *dot = strrchr(path, '.');
    if (dot && strcmp(dot, ".html") == 0) return "text/html; charset=utf-8";
    if (dot && strcmp(dot, ".js") == 0) return "text/javascript; charset=utf-8";
    if (dot && strcmp(dot, ".css") == 0) return "text/css; charset=utf-8";
    if (dot && strcmp(dot, ".txt") == 0) return "text/plain; charset=utf-8";
    if (dot && strcmp(dot, ".woff2") == 0) return "font/woff2";
    return "application/octet-stream";
}

static int is_prefix(const char *arg) { return strncmp(arg, "--prefix=", 9) == 0; }

int main(int argc, char **argv)
{
    FILE *out;
    const char *prefix = "/";
    int i, c;
    if (argc < 3) {
        fprintf(stderr, "usage: embed out.c file... [--prefix=/path/ file...]\n");
        return 2;
    }
    out = fopen(argv[1], "w");
    if (!out) return 1;
    fprintf(out, "/* generated by tools/embed.c from the web/ and web2/dist/ files: do not edit */\n"
                 "#include <stddef.h>\n"
                 "typedef struct { const char *path, *type; const unsigned char *data; size_t len; } XppWebAsset;\n");
    for (i = 2; i < argc; i++) {
        FILE *in;
        size_t n = 0;
        if (is_prefix(argv[i])) continue;
        in = fopen(argv[i], "rb");
        if (!in) {
            fprintf(stderr, "embed: cannot read %s\n", argv[i]);
            return 1;
        }
        fprintf(out, "static const unsigned char a%d[] = {", i);
        while ((c = fgetc(in)) != EOF) {
            fprintf(out, "%s%s%d", n ? "," : "", n % 24 ? "" : "\n", c);
            n++;
        }
        fprintf(out, "%s0};\n", n ? "," : "");
        fclose(in);
    }
    fprintf(out, "const XppWebAsset xpp_web_assets[] = {\n");
    for (i = 2; i < argc; i++) {
        const char *base;
        FILE *in;
        long len;
        if (is_prefix(argv[i])) {
            prefix = argv[i] + 9;
            continue;
        }
        base = strrchr(argv[i], '/');
        base = base ? base + 1 : argv[i];
        in = fopen(argv[i], "rb");
        fseek(in, 0, SEEK_END);
        len = ftell(in);
        fclose(in);
        fprintf(out, "  {\"%s%s\", \"%s\", a%d, %ld},\n", prefix, strcmp(base, "index.html") == 0 ? "" : base,
                type_of(base), i, len);
    }
    fprintf(out, "  {0, 0, 0, 0}\n};\n");
    fclose(out);
    return 0;
}
