#pragma once
/* Build tools cannot link the core's I/O (it is still being built).
   Own the byte-to-source conversion here, shared by both generators. */
#include <fstream>
#include <filesystem>
#include <iomanip>
#include <iostream>
#include <ostream>
#include <random>
#include <stdexcept>
#include <string>
#include <string_view>

namespace xpp::embed {
// Keep generated lines short enough to inspect without horizontal scrolling.
inline constexpr std::size_t bytes_per_line = 24;

class InputError : public std::runtime_error {
public:
    InputError(const char *path, const char *message)
        : std::runtime_error(std::string(path) + ":1: " + message) {}
};

inline void write_bytes(std::ostream &out, std::string_view symbol, const char *path)
{
    std::ifstream in(path, std::ios::binary);
    if (!in) throw InputError(path, "cannot open embedded file");
    out << "constexpr unsigned char " << symbol << "[] = {";
    std::size_t n = 0;
    char byte;
    while (in.get(byte)) {
        out << (n ? "," : "") << (n % bytes_per_line ? "" : "\n")
            << static_cast<unsigned int>(static_cast<unsigned char>(byte));
        ++n;
    }
    if (in.bad() || !in.eof()) throw InputError(path, "cannot read embedded file");
    // A spare byte permits empty inputs; spans exclude it from the payload.
    out << (n ? "," : "") << "0};\n";
}

/* Bootstrap equivalent of xpp::Writer: exclusive sibling, close, then rename.
   Never open the destination itself, including a device or symlink. */
class Output {
    std::filesystem::path target_;
    std::filesystem::path temporary_;
    std::ofstream stream_;
    bool owned_ = false;

    void discard() noexcept
    {
        if (!owned_) return;
        // Abandoned bytes will be removed; a flush error cannot make them usable.
        try { if (stream_.is_open()) stream_.close(); } catch (const std::exception &) {}
        std::error_code error;
        std::filesystem::remove(temporary_ / "output.cpp", error);
        if (error)
            std::cerr << target_.string() << ":1: cannot remove temporary output: "
                      << error.message() << '\n';
        std::filesystem::remove(temporary_, error);
        if (error)
            std::cerr << target_.string() << ":1: cannot remove temporary directory: "
                      << error.message() << '\n';
        owned_ = false;
    }

public:
    explicit Output(const char *path) : target_(path)
    {
        try {
            const auto status = std::filesystem::symlink_status(target_);
            if (std::filesystem::exists(status) && !std::filesystem::is_regular_file(status))
                throw std::runtime_error("output is not a regular file");
            temporary_ = target_;
            temporary_ += ".tmp-" + std::to_string(std::random_device{}());
            // Directory creation is exclusive on UCRT too (its noreplace open fails).
            owned_ = std::filesystem::create_directory(temporary_);
            if (!owned_) throw std::runtime_error("temporary output already exists");
            std::filesystem::permissions(temporary_, std::filesystem::perms::owner_all);
            stream_.exceptions(std::ios::failbit | std::ios::badbit);
            stream_.open(temporary_ / "output.cpp");
            stream_ << "// Generated by tools/embed*.cpp; do not edit.\n"
                       "#include \"xpp_assets.h\"\nnamespace xpp {\nnamespace {\n";
        } catch (...) {
            discard();
            throw;
        }
    }
    Output(const Output &) = delete;
    Output &operator=(const Output &) = delete;
    ~Output() { discard(); }

    std::ostream &stream() { return stream_; }
    void commit()
    {
        stream_.close();
        std::filesystem::rename(temporary_ / "output.cpp", target_);
    }
};

/* One error boundary for both tools: only InputError carries an input place;
   stream, open, close and commit errors belong to the destination. */
template <class Generate>
int generate(const char *path, const char *tool, Generate write)
{
    try {
        Output output(path);
        write(output.stream());
        output.commit();
        return 0;
    } catch (const InputError &error) {
        std::cerr << error.what() << '\n';
    } catch (const std::exception &error) {
        std::cerr << path << ":1: " << tool << ": " << error.what() << '\n';
    }
    return 1;
}
}
