#!/bin/sh
# Run every example ODE through xppautX -silent (tools/run_example.sh, one
# per model, several at once) and compare what each writes (output.dat's
# md5 with CRs removed, or "none" when the model does not run by itself:
# AUTO tests, includes) with a baseline. A model that exits nonzero or
# times out fails the check whatever the baseline says.
#
# A difference means the numerics changed: find why, and only when the
# change is intended, rewrite the baseline with --update and say so in the
# commit message.
#
# Baselines: tests/examples.md5 is Linux's (tools/verify.sh). A platform
# whose libm or compiler rounds a last digit differently has its own,
# tests/examples.<platform>.md5, generated by CI (W17): CI runs this with
# --platform <name> --write <file> and uploads the file as an artifact
# (examples-md5-<name>). With no tests/examples.<name>.md5 yet the platform
# is compared with Linux's and, in this first-run mode, a difference is
# reported, not failed: commit the artifact's file as
# tests/examples.<name>.md5 (only if some model differs: a platform that
# matches Linux exactly needs none), and do the same to regenerate it when
# numerics change on purpose.
#
# Usage: tools/examples_check.sh [--update] [--bin PATH] [--baseline FILE]
#                                [--platform NAME] [--write FILE] [--keep DIR]
#   --bin PATH       the binary (default ./xppautX, or ./xppautX.exe)
#   --baseline FILE  compare with FILE (default tests/examples.md5)
#   --platform NAME  compare with tests/examples.NAME.md5 when it exists,
#                    else with tests/examples.md5 in first-run mode
#   --write FILE     also write the md5s computed here to FILE
#   --update         write the md5s computed here as the baseline
#   --keep DIR       put the output.dat of each model that differs from the
#                    baseline in DIR (as <path with / made _>.dat), to see
#                    what changed (CI uploads it with the md5s)
# TIMEOUT=seconds per run (default 300: the slowest model takes ~12 s
# alone, several times that while other checks share the machine).
# JOBS=models run at once (default: the machine's core count).
cd "$(dirname "$0")/.." || exit 1
top=$PWD
base=tests/examples.md5
platform=
write=
keep=
update=0
bin=
while [ $# -gt 0 ]; do
  case "$1" in
    --update) update=1 ;;
    --bin) bin=$2; shift ;;
    --baseline) base=$2; shift ;;
    --platform) platform=$2; shift ;;
    --write) write=$2; shift ;;
    --keep) keep=$2; shift ;;
    *) echo "examples_check.sh: unknown option $1"; exit 2 ;;
  esac
  shift
done
if [ -z "$bin" ]; then
  if [ ! -e xppautX ] && [ -e xppautX.exe ]; then bin=xppautX.exe; else bin=xppautX; fi
fi
case "$bin" in /*) ;; *) bin=$top/$bin ;; esac
first_run=0
if [ -n "$platform" ]; then
  if [ -e "tests/examples.$platform.md5" ] || [ $update -eq 1 ]; then
    base=tests/examples.$platform.md5
  else
    first_run=1
  fi
fi
jobs=${JOBS:-$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 4)}
out=$(mktemp -d)
[ -n "$keep" ] && export KEEP_OUTPUT=1
find examples -name '*.ode' | sort \
  | xargs -P"$jobs" -I{} tools/run_example.sh {} "$bin" "${TIMEOUT:-300}" "$out" > "$out/failures" 2>&1
cat "$out"/*.sum | LC_ALL=C sort -k2 > "$out/all"
n=$(wc -l < "$out/all" | tr -d ' ')
if [ -n "$write" ]; then cp "$out/all" "$write"; echo "md5s written to $write"; fi
# a model that crashed or timed out (run_example.sh printed why)
failed=$(grep -l -v '^0$' "$out"/*.st 2>/dev/null | wc -l | tr -d ' ')
if [ "$failed" -ne 0 ]; then
  cat "$out/failures"
  rm -rf "$out"
  echo "EXAMPLES FAILED: $failed of $n models crashed or timed out"
  exit 1
fi
if [ $update -eq 1 ]; then
  mv "$out/all" "$base"
  rm -rf "$out"
  echo "examples baseline written to $base: $n models, $(grep -vc '^none' "$base") with output"
  exit 0
fi
bad=$(LC_ALL=C sort -k2 "$base" | diff - "$out/all" | grep '^[<>]')
if [ -n "$keep" ] && [ -n "$bad" ]; then
  mkdir -p "$keep"
  echo "$bad" | sed -n 's/^> [^ ]* //p' | while read -r f; do
    name=$(echo "$f" | tr / _)
    [ -e "$out/$name.dat" ] && cp "$out/$name.dat" "$keep/"
  done
  echo "the differing models' output.dat: $keep"
fi
rm -rf "$out"
if [ -n "$bad" ]; then
  echo "$bad"
  ndiff=$(echo "$bad" | grep -c '^>')
  if [ $first_run -eq 1 ]; then
    echo "FIRST RUN on $platform: no tests/examples.$platform.md5 yet; $ndiff of $n models differ from $base (above), not failed."
    echo "No model crashed. To compare $platform with itself from now on, commit this run's md5s${write:+ ($write)} as tests/examples.$platform.md5."
    exit 0
  fi
  echo "EXAMPLES DIFFER from $base: $ndiff of $n models"
  exit 1
fi
echo "examples ok: $n models, $(grep -vc '^none' "$base") outputs match $base${platform:+ ($platform)}"
